### PR TITLE
Added Greeting Bot

### LINKED ISSUE #8: Greeting bot
Adding a greeting bot to the repo that will greet everyone who creates a PR or opens an issue on this repo.

Please assign me under GSSOC'21.

### PR DESCRIPTION
**Pull request by aayushirai9900**
### Pull Request

This PR fixes : #8 

1. What type of change does your PR bring? 
    - [x] Feature Update

### CODE REVIEW

**Comment by alphaX86** [comment]
@aayushirai9900 have you tested it?

**Comment by aayushirai9900** [comment]
> @aayushirai9900 have you tested it?

Yesd

**Comment by aayushirai9900** [comment]
> @aayushirai9900 have you tested it?

Yess

**Review by alphaX86 — APPROVED** [review]
LGTM but we'll see how it works live....

**Pull request merged**
