### PR TITLE
correction in Readme

### PR DESCRIPTION
**Pull request by Varun8216889**
### Pull Request

This PR fixes 

1. What type of change does your PR bring? 
    - [ ] Bug fix
    - [ ] Feature Update
    - [ ] Issue fix
    - [ ] Doc fix/update
    - [ ] Other

2. Any else you want to convey? (Additional context)

### CODE REVIEW

**Comment by alphaX86** [comment]
Um.... @Varun8216889 the change is ok but I said to change the README under DatabaseConnection folder in the repo 🤣

**Comment by alphaX86** [comment]
Anyway, you still have time do it then

**Comment by Varun8216889** [comment]
ooh sorry, my bad

**Comment by Varun8216889** [comment]
what I have to add in about the feature.

**Comment by alphaX86** [comment]
> what I have to add in about the feature.

Just read the doc and change what word you feel to be inserted or replaced. Or if this is hard to you, just capitalize some letters that's all

**Comment by alphaX86** [comment]
Note: Change it in this [FILE](https://github.com/Srimathij/Indra_Bot/blob/main/DatabaseConnection/readme.md)

**Comment by alphaX86** [comment]
This is a bonus though, I'll merge it

**Comment by Varun8216889** [comment]
In the future, if u need someone to work on HTML or CSS.
Please let me know. I am searching for level 2 or 3 issues.

**Comment by alphaX86** [comment]
Hmm alright! 👍

**Pull request merged**
