### PR TITLE
feedback form

### LINKED ISSUE #36: feedback form [WEB]
## What UI bug/error you faced? Could you describe?
feedback form is not added

### PR DESCRIPTION
**Pull request by SuryaSachan**
### Pull Request

This PR fixes 

1. What type of change does your PR bring? 
    - [ ] Bug fix
    - [ ] Feature Update
    - [x] Issue fix
    - [ ] Doc fix/update
    - [ ] Other

2. Any else you want to convey? (Additional context)
Getform is used for Backend of the feedback form

### CODE REVIEW

**Comment by alphaX86** [comment]
Alright I solved the merge conflict! But one problem is still there. The nav link for the form is somewhat hidden, it's there but not visible as below...
image

**Review by alphaX86 — CHANGES_REQUESTED** [review]
Just do that change and I'll merge it @SuryaSachan

**Comment by SuryaSachan** [comment]
check now

**Review by alphaX86 — APPROVED** [review]
Works perfectly

**Pull request merged**
